version: 0.2

env:
  variables:
    #TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: nac@justice.gov.uk
    TF_VAR_enable_authentication: true
  parameter-store:
    TF_VAR_assume_role: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_radius_db_username: "/moj-network-access-control/radius_db_username"
    TF_VAR_radius_db_password: "/moj-network-access-control/radius_db_password"
    TF_VAR_azure_federation_metadata_url: "/moj-network-access-control/$ENV/azure_federation_metadata_url"
    TF_VAR_vpn_hosted_zone_domain: "/moj-network-access-control/$ENV/vpn_hosted_zone_domain"
    TF_VAR_vpn_hosted_zone_id: "/moj-network-access-control/$ENV/vpn_hosted_zone_id"
    TF_VAR_admin_db_username: "/moj-network-access-control/$ENV/admin_db_username"
    TF_VAR_admin_db_password: "/moj-network-access-control/$ENV/admin_db_password"
    TF_VAR_admin_sentry_dsn: "/moj-network-access-control/$ENV/admin_sentry_dsn"
    TF_VAR_transit_gateway_id: "/moj-network-access-control/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id: "/moj-network-access-control/$ENV/transit_gateway_route_table_id"
    TF_VAR_ocsp_endpoint: "/moj-network-access-control/$ENV/ocsp/endpoint"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform apply --auto-approve -no-color
      - ./scripts/publish_terraform_outputs.sh
